### ISSUE TITLE
TLS Client Hello

### ISSUE THREAD

**Issue by jonatron** [stevekerrison/dabao#17]
https://tlsfingerprint.io/
Found about about TLS fingerprinting recently, Client Hello details could be included if you want.

**Comment by stevekerrison** [comment]
Client Hello and other such fields would definitely be included at a certain level-of-detail if a TLS connection were to be simulated.

I find Ulfheim's byte-by-byte explanations to be very useful: https://tls13.ulfheim.net/ and https://tls.ulfheim.net/
